### ISSUE TITLE
specify dependency of ruby version (>= 2.3)

### ISSUE THREAD

**Issue by MathieuDerelle** [CareMessagePlatform/rspec-request_snapshot#10]
since the `&.` operator was introduced by ruby 2.3, you should add
`spec.required_ruby_version = '>= 2.3'`
to your gemspec

or avoid it to be compatible for older versions of ruby

```
An error occurred while loading ./spec/pdf/extract/utils/others_spec.rb.
Failure/Error: require 'rspec/request_snapshot'

SyntaxError:
  /Users/mathieu/.rvm/gems/ruby-2.2.9/gems/rspec-request_snapshot-0.5.0/lib/rspec/request_snapshot/matcher.rb:35: syntax error, unexpected '.'
        @options[:format]&.to_sym || RSpec.configuration...
                           ^
# /Users/mathieu/.rvm/gems/ruby-2.2.9/gems/rspec-request_snapshot-0.5.0/lib/rspec/request_snapshot.rb:6:in `require'
# /Users/mathieu/.rvm/gems/ruby-2.2.9/gems/rspec-request_snapshot-0.5.0/lib/rspec/request_snapshot.rb:6:in `<top (required)>'
# ./spec/spec_helper.rb:6:in `require'
# ./spec/spec_helper.rb:6:in `<top (required)>'
# ./spec/pdf/extract/utils/others_spec.rb:1:in `require'
# ./spec/pdf/extract/utils/others_spec.rb:1:in `<top (required)>'
```

**Comment by bruno-campos** [comment]
This will be fixed in the next version. Thanks for the heads up :)
