### ISSUE TITLE
allow arrays in payloads

### ISSUE THREAD

**Issue by MathieuDerelle** [CareMessagePlatform/rspec-request_snapshot#11]
test
```
  it 'foo' do
    expect(JSON.generate({ foo: [] })).to match_snapshot("foo")
  end
```

error
```  1) PDF::Extract foo
     Failure/Error: expect(JSON.generate({ foo: [] })).to match_snapshot("foo")
     
     NoMethodError:
       undefined method `each_key' for []:Array
       Did you mean?  each_entry
     # /Users/mathieu/.rvm/gems/ruby-2.3.3/gems/rspec-request_snapshot-0.5.0/lib/rspec/request_snapshot/handlers/json.rb:19:in `deep_transform_values'
     # /Users/mathieu/.rvm/gems/ruby-2.3.3/gems/rspec-request_snapshot-0.5.0/lib/rspec/request_snapshot/handlers/json.rb:9:in `comparable'
     # /Users/mathieu/.rvm/gems/ruby-2.3.3/gems/rspec-request_snapshot-0.5.0/lib/rspec/request_snapshot/matcher.rb:18:in `block (2 levels) in <module:RequestSnapshot>'
     # ./spec/pdf/extract_spec.rb:129:in `block (2 levels) in <top (required)>'
```

**Comment by bruno-campos** [comment]
This seems to not be happening anymore. Probably it was fixed in the past version. Feel free to reopen it in case it happens again

**Comment by MathieuDerelle** [comment]
I'm still having this issue
```
  2) PDF::Extract foo
     Failure/Error: expect(JSON.generate({ foo: [] })).to match_snapshot("foo")
     
     NoMethodError:
       undefined method `each_key' for []:Array
     # /Users/mathieu/.rvm/gems/ruby-2.2.9/gems/rspec-request_snapshot-0.6.1/lib/rspec/request_snapshot/handlers/json.rb:19:in `deep_transform_values'
     # /Users/mathieu/.rvm/gems/ruby-2.2.9/gems/rspec-request_snapshot-0.6.1/lib/rspec/request_snapshot/handlers/json.rb:9:in `comparable'
     # /Users/mathieu/.rvm/gems/ruby-2.2.9/gems/rspec-request_snapshot-0.6.1/lib/rspec/request_snapshot/matcher.rb:18:in `block (2 levels) in <module:RequestSnapshot>'
     # ./spec/pdf/extract_spec.rb:133:in `block (2 levels) in <top (required)>'
```

Gemfile.lock
```
    rspec (3.8.0)
      rspec-core (~> 3.8.0)
      rspec-expectations (~> 3.8.0)
      rspec-mocks (~> 3.8.0)
    rspec-core (3.8.0)
      rspec-support (~> 3.8.0)
    rspec-expectations (3.8.1)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.8.0)
    rspec-mocks (3.8.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.8.0)
    rspec-request_snapshot (0.6.1)
      rspec (~> 3.0)
    rspec-support (3.8.0)
```
